name: mlpr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  http: ^1.3.0
  image: ^3.2.1
  flutter_dotenv: ^5.0.2
  dio: ^5.2.0
  flutter_secure_storage: ^6.0.0  # หรือเวอร์ชั่นล่าสุดที่รองรับ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
